---
title: "aapi-edu-map"
author: "suzanne"
date: "5/9/2022"
output: html_document
---


# to determine the threshold for reporting, I'm assuming the 5 year CS has roughly a 10% sample rate of the population, if the population of adults is 300 then the MOE is around 15%; it looks like the map ranges from shares around 10% to 97% so there is truly a wide range, and for rough story telling it should be okay.
```{r}
library(psrccensus)
library(dplyr)
library(tidyr)
edu<-get_acs_recs(geography = 'tract',
             table.names = 'C15002D',
             years = 2019,
             acs.type = 'acs5')%>% select('GEOID', 'label', 'estimate', 'moe')%>%filter(
label=='Estimate!!Total:!!Male:!!Bachelor\'s degree or higher' | label==
'Estimate!!Total:!!Female:!!Bachelor\'s degree or higher' | label==
'Estimate!!Total:')%>% pivot_wider(names_from=label, values_from=c(estimate, moe))%>%mutate('Total Bachelor\'s degree or higher'=`estimate_Estimate!!Total:!!Male:!!Bachelor's degree or higher` +`estimate_Estimate!!Total:!!Female:!!Bachelor's degree or higher`)%>%mutate(tots_with_not_enough_data=ifelse(`estimate_Estimate!!Total:`>300,`estimate_Estimate!!Total:`,NaN))%>% mutate('share_unformatted'= `Total Bachelor's degree or higher`/tots_with_not_enough_data)%>%mutate('estimate'=round(share_unformatted*100,0))

tract.lyr.url <- "https://services6.arcgis.com/GWxg6t7KXELn1thE/arcgis/rest/services/Census_Tracts_2010/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"
tract.lyr <- sf::st_read(tract.lyr.url)

```

```{r}

create_tract_map_share_edu <- function(tract.tbl, tract.lyr,
                             map.title = NULL, map.subtitle = NULL,
                             map.title.position = NULL,
                             legend.title = NULL, legend.subtitle = NULL,
                             map.lat=47.615, map.lon=-122.257, map.zoom=8.5, wgs84=4326){


  # Summarize and Aggregate Tract Data by Year and Attribute to Map and join to tract layer for mapping
  # rename census value column to estimate to match ACS
  # also allow for the easy mapping of equity geographies
  tbl <- tract.tbl %>%
    dplyr::rename_at(dplyr::vars(matches("value")),function(x) "estimate") %>%
    dplyr::rename_at(dplyr::vars(matches("equity_geog_vs_50_percent")),function(x) "estimate") %>%
    dplyr::rename_at(dplyr::vars(matches('equity_geog_vs_reg_total')),function(x) "estimate") %>%
    dplyr::rename_at(dplyr::vars(matches("geoid")),function(x) "GEOID") %>%
    dplyr::select(.data$GEOID,.data$estimate) %>%
    dplyr::mutate(dplyr::across(c('GEOID'), as.character))%>%
    dplyr::group_by(.data$GEOID) %>%
    dplyr::summarise(Share=sum(.data$estimate))

    tract.lyr<-tract.lyr%>%
    # make geo names across 2010 and 2020
    dplyr::rename_at(dplyr::vars(matches("geoid10")),function(x) "geoid") %>%
    dplyr::rename_at(dplyr::vars(matches("geoid20")),function(x) "geoid")

  c.layer <- dplyr::left_join(tract.lyr,tbl, by = c("geoid"="GEOID")) %>%
    sf::st_transform(wgs84)

  pal <- leaflet::colorNumeric(palette="Purples", domain = c.layer$Share, na.color = "#76787A")

  labels <- paste0("Census Tract: ", c.layer$geoid, '<p></p>',
                   'Share: ', paste(c.layer$Share, "%", sep=""))%>% lapply(htmltools::HTML)

  css_fix <- "div.info.legend.leaflet-control br {clear: both;}" # CSS to correct spacing of NA icon & text
  html_fix <- htmltools::tags$style(type = "text/css", css_fix)  # Convert CSS to HTML

  m <- leaflet::leaflet() %>%
    leaflet::addMapPane(name = "polygons", zIndex = 410) %>%
    leaflet::addMapPane(name = "maplabels", zIndex = 500) %>% # higher zIndex rendered on top

    leaflet::addProviderTiles("CartoDB.VoyagerNoLabels") %>%
    leaflet::addProviderTiles("CartoDB.VoyagerOnlyLabels",
                              options = leaflet::leafletOptions(pane = "maplabels"),
                              group = "Labels") %>%

    leaflet::addEasyButton(leaflet::easyButton(icon="fa-globe",
                                               title="Region",
                                               onClick=leaflet::JS("function(btn, map){map.setView([47.615,-122.257],8.5); }"))) %>%
    leaflet::addPolygons(data=c.layer,
                         fillOpacity = 0.7,
                         fillColor = pal(c.layer$Share),
                         weight = 0.7,
                         color = "#BCBEC0",
                         group="Population",
                         opacity = 0,
                         stroke=FALSE,
                         options = leaflet::leafletOptions(pane = "polygons"),
                         dashArray = "",
                         highlight = leaflet::highlightOptions(
                           weight =5,
                           color = "76787A",
                           dashArray ="",
                           fillOpacity = 0.7,
                           bringToFront = TRUE),
                         label = labels,
                         labelOptions = leaflet::labelOptions(
                           style = list("font-weight" = "normal", padding = "3px 8px"),
                           textsize = "15px",
                           direction = "auto")) %>%
    leaflet::addLegend(pal = pal,
                       values = c.layer$Share,
                       position = "bottomright",
                       title = paste(legend.title, '<br>', legend.subtitle),
                       labFormat=leaflet::labelFormat(suffix='%'),
                       na.label='Not enough data to report')%>%

    leaflet::addControl(html = paste(map.title, '<br>', map.subtitle),
                        position = map.title.position,
                        layerId = 'mapTitle') %>%

    leaflet::addLayersControl(baseGroups = "CartoDB.VoyagerNoLabels",
                              overlayGroups = c("Labels", "Population")) %>%

    leaflet::setView(lng=map.lon, lat=map.lat, zoom=map.zoom)

  m <- m %>% htmlwidgets::prependContent(html_fix) # Insert into leaflet HTML code
  
  return(m)

}
```

```{r}
m<-create_tract_map_share_edu(tract.tbl=edu, tract.lyr=tract.lyr,  
                 legend.title='Share of Asian Alone Adults', legend.subtitle='with Bachelor\'s degree or higher')
m
```

