---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggiraph)
library(openxlsx)
library(pals)
```

```{r read excel}
filepath <- file.path('data','AsianPacificIslanderMedianIncome.xlsx')
tabs <- getSheetNames(filepath)
tabList <- map(tabs, ~read.xlsx(xlsxFile = filepath, sheet = .x))
names(tabList) <- tabs
```

```{r subgroup data}
sg <- tabList[[1]]

# clean data frame
colnames(sg) <- c('year', 'county', 'worker_race', 'median_earn', 'median_earn_moe')
sg <- sg %>% 
  mutate(label = str_to_title(worker_race),
         sort = ifelse(label %in% str_subset(label, 'All.*'), '2', '1'),
         lower = median_earn - median_earn_moe,
         upper = median_earn + median_earn_moe) %>% 
  arrange(label)

# arrange labels
label_a <- unique(sg$label)[!(unique(sg$label) %in% str_subset(unique(sg$label), 'All.*'))]
all_labels <- c(label_a, str_subset(unique(sg$label), 'All.*'))
sg_alpha <- sg %>%
  mutate(label = factor(label, levels = all_labels),
         fill = ifelse(label %in% str_subset(unique(sg$label), '.*Region.*'), '1', '2')) %>% 
  arrange(label)
```

```{r plot detail}
plot_title <- 'Median Worker Annual Earnings'
plot_subtitle <- 'Asian Alone Groups and Total Regional '
plot_source <- 'Source: 2015-19 PUMS'

gridline.color <- '#ededed'
background.color <- 'white'
```

```{r plot subgroup horizontal, eval=FALSE}
g <- ggplot(sg_alpha) +
  geom_col_interactive(aes(label, median_earn, fill = fill, 
                           tooltip = paste0(label,': $', median_earn))) +
  geom_linerange_interactive(aes(x = label, ymin = lower, ymax = upper)) +
  scale_y_continuous(labels = scales::label_dollar()) +
  scale_fill_manual(values = c( '#f05a28', '#bcbec0')) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   vjust = 1.05,
                                   size = 7),
        legend.position = 'none',
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = background.color),
        panel.grid.major.y = element_line(color = gridline.color),
        panel.grid.minor.y = element_line(color = gridline.color),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.caption = element_text(size=5)) +
  labs(x = NULL,
       y = NULL,
       title = plot_title,
       subtitle = plot_subtitle,
       caption = plot_source)

ggiraph(ggobj = g)
  
```

```{r plot subgroup vertical}

df_high_low <- sg_alpha %>% 
  arrange(desc(median_earn)) %>% 
  mutate(label = str_to_title(worker_race)) %>% 
  mutate(label = factor(label, level = label))

h <- ggplot(df_high_low) +
  geom_col_interactive(aes(label, median_earn, fill = worker_race, 
                           tooltip = paste0(label,': $', prettyNum(median_earn, big.mark=",",scientific=FALSE)))) +
  geom_linerange_interactive(aes(x = label, 
                                 ymin = lower, 
                                 ymax = upper,
                                 tooltip = paste0(label, ': Lower MOE: $',  prettyNum(lower, big.mark=",",scientific=FALSE), ', Upper MOE: $', prettyNum(upper, big.mark=",",scientific=FALSE)))) +
  scale_fill_manual(values = pals::brewer.pastel1(24)) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 35)) +
  scale_y_continuous(labels = scales::label_dollar()) +
  theme(axis.title = element_text(size = 8),
        axis.text.y = element_text(size = 5),
        axis.text.x = element_text(size = 7),
        legend.position = 'none',
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = background.color),
        panel.grid.major.x = element_line(color = gridline.color),
        panel.grid.minor.x = element_line(color = gridline.color),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.caption = element_text(size=5)) +
  labs(x = 'Person Detailed Race',
       y = 'Median Worker Earnings',
       title = plot_title,
       subtitle = plot_subtitle,
       caption = plot_source) +
  coord_flip()


plot_h <- ggiraph(ggobj = h)

plot_h

htmltools::save_html(plot_h, "median-worker-annual-earn.html")
```

```{r broadrace}
br <- tabList[[2]]

# clean data frame
colnames(br) <- c('worker_race', 'median_earn', 'median_earn_moe')
br <- br %>% 
  mutate(label = str_to_title(worker_race),
         sort = ifelse(label %in% str_subset(label, 'Total.*'), '3', '1'),
         sort = ifelse(label %in% str_subset(label, 'Two.*'), '2', sort),
         lower = median_earn - median_earn_moe,
         upper = median_earn + median_earn_moe) %>% 
  arrange(desc(median_earn))

br <- br %>% 
  mutate(label = factor(label, levels = label))
```

```{r plot broadrace}
plot_title_br <- 'Median Worker Annual Earnings'
# plot_subtitle_br <- 'Asian Alone Groups and Total Regional'
plot_source_br <- 'Source: 2015-19 PUMS'

i <- ggplot(br) +
  geom_col_interactive(aes(label, median_earn, fill = worker_race, 
                           tooltip = paste0(label,': $', prettyNum(median_earn, big.mark=",",scientific=FALSE)))) +
  geom_linerange_interactive(aes(x = label, 
                                 ymin = lower, 
                                 ymax = upper,
                                 tooltip = paste0(label, ': Lower MOE: $',  prettyNum(lower, big.mark=",",scientific=FALSE), ', Upper MOE: $', prettyNum(upper, big.mark=",",scientific=FALSE)))) +
  scale_fill_manual(values = pals::brewer.pastel1(9)) +
  scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 35)) +
  scale_y_continuous(labels = scales::label_dollar()) +
  theme(axis.title = element_text(size = 8),
        axis.text.y = element_text(size = 5),
        axis.text.x = element_text(size = 7),
        legend.position = 'none',
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = background.color),
        panel.grid.major.x = element_line(color = gridline.color),
        panel.grid.minor.x = element_line(color = gridline.color),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.caption = element_text(size=5)) +
  labs(x = 'Person Broad Race',
       y = 'Median Worker Earnings',
       title = plot_title_br,
       # subtitle = plot_subtitle_br,
       caption = plot_source_br) +
  coord_flip()


plot_i <- ggiraph(ggobj = i)

plot_i

htmltools::save_html(plot_i, "median-worker-annual-earn_broad.html")
```

