---
title: "Black History Month ACS Data"
author: "suzanne"
date: "8/19/2021"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes for Black History Month

```{r load_libraries}
library(devtools)
library(sf)
library(dplyr)
library(psrccensus)
library(ggplot2)
library(tidycensus)
Sys.getenv("CENSUS_API_KEY")
```

What can we find?
```{r}
var_list<- load_variables(2019, "acs5", cache = TRUE)
```


### Educational Attainment

```{r}




Black_df <- get_acs_recs(geography = 'county',
             table.names = c('C15002B'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')



white_df <- get_acs_recs(geography = 'county',
             table.names = c('C15002H'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')


white_Black_df<-merge(Black_df, white_df, by='label')

Black_white_df_formatted<-white_Black_df %>% select(label,estimate.x, moe.x, estimate.y, moe.y) %>% rename(Black_Educational_Attainment=estimate.x, Black_Educational_Attainment_MOE=moe.x, White_Educational_Attainment=estimate.y, White_Educational_Attainment_MOE=moe.y)





write.table(Black_white_df_formatted,"clipboard", sep='\t', row.names=FALSE )


Black_white_df_formatted


```

### Where were people born?

```{r}


nativity_df_Black<- get_acs_recs(geography = 'county',
             table.names = c('B06004B'),
             years=c(2019),
             acs.type = 'acs5')



nativity_df_Black_formatted<-nativity_df_Black 

nativity_df_Black_formatted
write.table(nativity_df_Black_formatted,"clipboard", sep='\t', row.names=FALSE )

```
```{r}

ancestry_df<- get_acs_recs(geography = 'county',
             table.names = c('B04006'),
             years=c(2019),
             acs.type = 'acs5')%>%
  filter(name=='Region')


write.table(ancestry_df,"clipboard", sep='\t', row.names=FALSE )
```

### Median Income

```{r}


income_df_Black<- get_acs_recs(geography = 'county',
             table.names = c('B19013B'),
             years=c(2019),
             acs.type = 'acs1')


income_df_white <- get_acs_recs(geography = 'county',
             table.names = c('B19013H'),
             years=c(2019),
             acs.type = 'acs1')

Black_white_df<-merge(income_df_Black,income_df_white, by ='name')

Black_white_df_formatted<-Black_white_df %>% select(name, estimate.x, moe.x, estimate.y, moe.y) %>% rename(County= name, white_nonhispanic_median_income=estimate.x, white_nonhispanic_median_income_moe=moe.x, black_median_income=estimate.y, black_median_income_moe=moe.y)

Black_white_df_formatted
write.table(Black_white_df_formatted,"clipboard", sep='\t', row.names=FALSE )

```

## Homeownership

```{r}


homeownership_black<-get_acs_recs(geography = 'county',
             table.names = c('B25003B'),
             years=c(2019),
             acs.type = 'acs1')

homeownership_white<-get_acs_recs(geography = 'county',
             table.names = c('B25003H'),
             years=c(2019),
             acs.type = 'acs1')


homeownership_df_black_white<- merge(homeownership_black, homeownership_white, by=c('label','name'))
write.table(homeownership_df_black_white,"clipboard", sep='\t', row.names=FALSE )

homeownership_df_black_white

```

### Median Age by Black and All

```{r}

Black_age_df<-get_acs_recs(geography = 'county',
             table.names = c('B01002B'),
             years=c(2019),
             acs.type = 'acs5')


white_age_df <- get_acs_recs(geography = 'county',
             table.names = c('B01002H'),
             years=c(2019),
             acs.type = 'acs5')


white_Black_df<-merge(Black_age_df, white_age_df, by=c('name','label'))%>% filter(label=='Estimate!!Median age --!!Total:')%>%
  select(name,estimate.x, estimate.y, )%>% rename('County'='name', 'Black population' ='estimate.x', 'White Population'='estimate.y')

write.table(white_Black_df,"clipboard", sep='\t', row.names=FALSE )
white_Black_df

```



### Poverty Rates

```{r}


poverty_df_Black<- get_acs_recs(geography = 'county',
             table.names = c('B17020B'),
             years=c(2019),
             acs.type = 'acs5')
poverty_df_white <- get_acs_recs(geography = 'county',
             table.names = c('B17020H'),
             years=c(2019),
             acs.type = 'acs5')

poverty_df_white<- poverty_df_white %>% filter(label=='Estimate!!Total:' | label=='Estimate!!Total:!!Income in the past 12 months below poverty level:')%>%select(name, estimate,moe,label)%>%tidyr::pivot_wider(names_from=label,values_from=c(estimate,moe) )

poverty_df_black<- poverty_df_Black %>% filter(label=='Estimate!!Total:' | label=='Estimate!!Total:!!Income in the past 12 months below poverty level:')%>%select(name, estimate,moe,label)%>%tidyr::pivot_wider(names_from=label,values_from=c(estimate,moe) )

poverty_df_black_white<- merge(poverty_df_black, poverty_df_white, by='name')

write.table(poverty_df_black_white,"clipboard", sep='\t', row.names=FALSE )

```



### Means of Transportation to Work

```{r}

white_transport_df <- get_acs_recs(geography = 'county',
             table.names = c('B08105A'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')



Black_transport_df <- get_acs_recs(geography = 'county',
             table.names = c('B08105B'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')



white_Black_df<-merge(Black_transport_df, white_transport_df, by='label')%>% 
  select(estimate.x, moe.x, label, estimate.y, moe.y)




write.table(white_Black_df,"clipboard", sep='\t', row.names=FALSE )


white_Black_df
```

### B25014, Occupants per room
```{r}
white_df <- get_acs_recs(geography = 'county',
             table.names = c('B25014H'),
             years=c(2019),
             acs.type = 'acs5')



Black_df <- get_acs_recs(geography = 'county',
             table.names = c('B25014B'),
             years=c(2019),
             acs.type = 'acs5')
```




```{r}
white_Black_df<-merge(Black_df, white_df, by='label')%>% 
  select(estimate.x, moe.x, label, estimate.y, moe.y)




write.table(white_Black_df,"clipboard", sep='\t', row.names=FALSE )


white_Black_df
```

```{r}
white_df <- get_acs_recs(geography = 'county',
             table.names = c('B25032H'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')



Black_df <- get_acs_recs(geography = 'county',
             table.names = c('B25032B'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')

white_Black_df<-merge(Black_df, white_df, by='label')%>% 
  select(estimate.x, moe.x, label, estimate.y, moe.y)

write.table(white_Black_df,"clipboard", sep='\t', row.names=FALSE )%>%filter(name=='Region')
```

# Computers at home
```{r}
Black_df <- get_acs_recs(geography = 'county',
             table.names = c('B28009B'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')


white_df <- get_acs_recs(geography = 'county',
             table.names = c('B28009H'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')




white_Black_df<-merge(Black_df, white_df, by='label')%>% 
  select(estimate.x, moe.x, label, estimate.y, moe.y)

write.table(white_Black_df,"clipboard", sep='\t', row.names=FALSE )%>%filter(name=='Region')
```
# Job sector

```{r}
Black_df <- get_acs_recs(geography = 'county',
             table.names = c('C24010B'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')


white_df <- get_acs_recs(geography = 'county',
             table.names = c('C24010H'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')




white_Black_df<-merge(Black_df, white_df, by='label')%>% 
  select(estimate.x, moe.x, label, estimate.y, moe.y)

write.table(white_Black_df,"clipboard", sep='\t', row.names=FALSE )
white_Black_df
```


# Health Insurance
```{r}
Black_df <- get_acs_recs(geography = 'county',
             table.names = c('C27001B'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')


white_df <- get_acs_recs(geography = 'county',
             table.names = c('C27001H'),
             years=c(2019),
             acs.type = 'acs5')%>%filter(name=='Region')




white_Black_df<-merge(Black_df, white_df, by='label')%>% 
  select(estimate.x, moe.x, label, estimate.y, moe.y)
white_Black_df

write.table(white_Black_df,"clipboard", sep='\t', row.names=FALSE )
```

```{r}
foreign_born<-get_acs_recs(geography = 'tract',
             table.names = 'B05006',
             years = 2019,
             acs.type = 'acs5')

foreign_born_Africa <- foreign_born %>% filter(label=='Estimate!!Total:!!Africa:')

             
gdb.nm <- paste0("MSSQL:server=",
"AWS-PROD-SQL\\Sockeye",
";database=",
"ElmerGeo",
";trusted_connection=yes")

spn <-  2285
wgs84=4326

tract_layer_name <- "dbo.tract2010_nowater"

tract.lyr <- st_read(gdb.nm, tract_layer_name, crs = spn)



m<-psrccensus::create_tract_map(tract.tbl=foreign_born_Africa, tract.lyr=tract.lyr,  
                 legend.title='African Foreign Born Population', legend.subtitle='by Census Tract')

```


